-- APENAS ESSAS TRÊS PRIMEIRAS SÃO NECESSÁRIAS PARA O PROJETO
DROP DATABASE IF EXISTS DBUNION;
CREATE DATABASE DBUNION;
USE DBUNION;

/*
CREATE TABLE COORDENADOR(
	IDCOORDENADOR INT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(255),
    EMAIL VARCHAR(255),
    CPF VARCHAR(255),
    CEP VARCHAR(255),
    TELEFONE INT,
	PRIMARY KEY(IDCOORDENADOR)
);

CREATE TABLE FUNCIONARIO(
	IDFUNCIONARIO INT NOT NULL AUTO_INCREMENT,
    IDCOODENADOR INT NOT NULL,
    NOME VARCHAR(255),
    EMAIL VARCHAR(255),
    CPF VARCHAR(255),
    CEP VARCHAR(255),
    TELEFONE INT,
	PRIMARY KEY(IDFUNCIONARIO),
    FOREIGN KEY(IDCOORDENADOR) REFERENCES COORDENADOR (IDCOORDENADOR)
);
*/

-- SELECT * FROM dbunion.coordenador;